apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: dell-csi-operator-controller-manager
  namespace: dell-csi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: OPERATOR_DRIVERS
          value: unity,powermax,isilon,vxflexos,powerstore
        image: dellemc/dell-csi-operator:v1.5.0
        imagePullPolicy: Always
        name: dell-csi-operator-controller
        volumeMounts:
        - mountPath: /etc/config/configmap
          name: configmap-volume
        - mountPath: /etc/config/dell-csi-operator
          name: config-dir
      initContainers:
      - command:
        - sh
        - -c
        - 'if [ -e /configmap/config.tar.gz ]; then /bin/tar -C /etc/config/dell-csi-operator -xzvf /configmap/config.tar.gz --strip-components 1; else echo "Warning: ConfigMap not mounted"; fi'
        image: docker.io/busybox:1.32.0
        name: config-copy
        volumeMounts:
        - mountPath: /configmap
          name: configmap-volume
        - mountPath: /etc/config/dell-csi-operator
          name: config-dir
      serviceAccountName: dell-csi-operator-manager-service-account
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: dell-csi-operator-config
          optional: true
        name: configmap-volume
      - emptyDir: null
        name: config-dir

