apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dell-csi-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dell-csi-operator-manager-role
subjects:
- kind: ServiceAccount
  name: dell-csi-operator-manager-service-account
  namespace: dell-csi-operator

