apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
  name: certified-operators
  namespace: openshift-marketplace
spec:
  displayName: Certified Operators
  icon:
    base64data: ""
    mediatype: ""
  image: registry.redhat.io/redhat/certified-operator-index:v4.6
  priority: -200
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m0s
